# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = 2048
  end

  config.vm.define "ahayonS" do |server|
    server.vm.hostname = "ahayonS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provision "shell", path: "scripts/setup.sh"
  end
end
