# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  # le node server gere le cluster avec le control plane et l'api Kubernetes
  config.vm.define "ahayonS" do |server| 
    server.vm.hostname = "ahayonS"
    # virtualbox ajoute une interface reseau supplementaire a la vm
    # les deux vms seront sur le meme reseau prive de base de virtualbox
    # et pourront communiquer avec ces adresses
    server.vm.network "private_network", ip: "192.168.56.110" 

    server.vm.provision "shell", inline: <<-SHELL
      echo "Mise a jour du systeme et installation de curl..."
      apt-get update
      apt-get install -y curl
  
      # token = secret partage pour permettre a un agent de rejoindre le cluster
      echo "Installation de K3s (Server)..."
      # 644 pour autoriser user non root a lire le kubeconfig et pouvoir utiliser les commandes kubectl
      curl -sfL https://get.k3s.io | \
      K3S_KUBECONFIG_MODE="644" \
      K3S_TOKEN="Tsais42" \
      INSTALL_K3S_EXEC="server --node-ip=192.168.56.110" \
      sh -
      SHELL
  end

  # l'agent est la pour fournir des ressources d'exec au cluster (CPU / RAM / execution de pods)
  config.vm.define "ahayonSW" do |serverworker|
    serverworker.vm.hostname = "ahayonSW"
    serverworker.vm.network "private_network", ip: "192.168.56.111"

    serverworker.vm.provision "shell", inline: <<-SHELL
      echo "Mise a jour du systeme et installation de curl..."
      apt-get update
      apt-get install -y curl

      echo \n\n"Installation de K3s (Agent)..."
      curl -sfL https://get.k3s.io | \
      K3S_URL="https://192.168.56.110:6443" \
      K3S_TOKEN="Tsais42" \
      INSTALL_K3S_EXEC="agent --node-ip=192.168.56.111" \
      sh -
    SHELL
  end
end