# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  # le node server gere le cluster avec le control plane et l'api Kubernetes
  config.vm.define "ahayonS" do |server| 
    server.vm.hostname = "ahayonS"
    # virtualbox ajoute une interface reseau supplementaire a la vm
    # les deux vms seront sur le meme reseau prive de base de virtualbox
    # et pourront communiquer avec ces adresses
    server.vm.network "private_network", ip: "192.168.56.110" 

    server.vm.provision "shell", path: "scripts/server.sh"
  end

  # l'agent est la pour fournir des ressources d'exec au cluster (CPU / RAM / execution de pods)
  config.vm.define "ahayonSW" do |serverworker|
    serverworker.vm.hostname = "ahayonSW"
    serverworker.vm.network "private_network", ip: "192.168.56.111"

    serverworker.vm.provision "shell", path: "scripts/worker.sh"
  end
end